export const UserFields = {
    EMAIL : 'EMAIL',
    NAME : 'NAME',
    MOBILE_NO : 'MOBILE_NO',
    DESIGNATION:'DESIGNATION',
    USER_TYPE:'USER_TYPE',
    ADMINISTRATIVE_LEVEL_ORDER:'ADMINISTRATIVE_LEVEL_ORDER',
    ROLES:'ROLES',
    STATUS : 'GLOBAL_STATUS',
    ACTION : 'GLOBAL_ACTION',
    LEVEL_OFFICE_TYPE:'LEVEL_OFFICE_TYPE',
    SCHEME: 'SCHEME',
    OFFICE:'OFFICE'
}
